[gdrive]
type = "service_account"
project_id = "shiva-pdf"
private_key_id = "f5d0f5a2a433eab2b1941af89d87f76693d49b52"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCfocBKSlGIaHG9
XJ5tjSTlMvBfu1GofXTS+AU/bEuQSslyk80mNNauRHMhwmRn0y0+i736tj72hOxV
aqdwJRtVfuzyVYEPEBYt1aKRaBJ6p6vwkmGHPZ8DdHIt3ttokOIaBNoYkLWf6+5p
3/4BpjJ/7vRNIR3TkV99jJfHOi3sN+T1TJ8OJzS1EjRyYuX00RGv2DnEpXkZFk4a
OidmFGlwh3EenJ0YZLSoC6UOWK9m8MGktixXhmiXnsRK29d7JslWjWnvE7GEQ+9H
XNNwRl7Ph5+0IW80PHlEvcU15Cq0zGry/LCNYFWfWvGn/tdvVHNJgqUle+cdPOsO
q88kaNMrAgMBAAECggEAELt+MetPV4qHHY+3RYltbB7mRkqWuSAJXlHEDw1VcFb+
faWTc+VG+XZQUSIUrzNaAzvXmo9+0w1EzoFC8sTY9CG9SXt/7ynDAWPqye4MPdIU
ej+FvIzPfae3jipVekTxhkOq7rdAanZrA6sIb3jRw0ozTmBhxXrv9POHN0lYZfGd
gaiZjqXnw1BGDlW/wziSSdRPS9ozK+4H3NiQ2EkjvGF39QfLYi6CjXiZUxsDP1DP
vxnpohP12iz5cFYWEmjydeT7rAxKgdOZE+UgWNz1EQ/tT0SsZzxL1jjHyx44+zpc
nYTq+w9U6oYvgzWOrY4jyRAL7RkAhxekBPZlq/vQWQKBgQDTAFPENCOfpqRXshZ7
7Czi9al0cNOvGpbyFa80xi0EvqpqNdZ/xQ2PNe2sFv6glOGdjJNye2BsYb3b6yMF
1uWEk5R0bGlZ3YI+ZeNhyVzvOpFP+ZjB00MeYjH62/qFY8NqtI3dNBTHWoDHL8+1
ym1jhy40YpDSSN+9o7+Zo4U1yQKBgQDBrOU1I2k/aRitO5UPm8Y+U62tFGlGcI/N
MyDOe2I0Bj65758ZnlLtLK8+Yq83cnNY8ONwdu4R5PFgBibZyM/3Mq4R9kQ2Xkni
PXVV7SWyqQe895hcJFWkWsMq2xOfVlBta2l1kb3jprDWGk7ZYX6vWA2PhO29wOxj
HUge+wLLUwKBgCWs60gfXzUElleqTuV1uFYWM1m9Q68Cem1jfdNYh3VPbjJkxpYt
40vs/zE5MeIOc3KkRTet2/u+QB5ij/Bc/MJ9b4aSTQVkzfrCSqWNRPDablPvZ11E
kbl9Ixt95++lbqFA+AvFXuhxuojWeqolKP8ahh+Icf96T6kW8gFG92QxAoGAO6vp
ctXWN5NJ5xXUd1qnWcyuVgVT6kAEDlUSZovdVeoWqXMKsfn10t1RoQcGtS6uG1kc
uinqb9j6BXvfvHoCmUckGqSln5qtaOdGn5LRapppp+8hIkKPoHPWbf3RreYKIaxW
ccLVnq5dDZpNcOx4+81FYFK0bSJjsqXy8pij48ECgYB8jo+mPn0mLSbREuTjoyM9
uZgZe73ZYU/1gNkW3EmKz/UY4QHQRzgu6Cokxy2d29x8OBvhlOs5JyKWnRbbiHLr
ZJ/xXkrzPd9x27BODMF/wC8rqrN17+E+fLlnNpX7wQS3Bno180BAYl2kSMQfJACH
n0zqLhzBNybQ6JAAyx2xWw==
-----END PRIVATE KEY-----"""
client_email = "shiva-uploader@shiva-pdf.iam.gserviceaccount.com"
client_id = "105806478207420166843"
auth_uri = "https://accounts.google.com/o/oauth_
